language: node_js
node_js: "stable"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      script:
        - npm run dist:publish-mwl

notifications:
  email: false